project:
  type: website

website:
  navbar: true
  title: "Military Doctrines"
  favicon: images/favicon.ico
  bread-crumbs: true

  page-footer:
    right: "This website is built with [Quarto](https://quarto.org/) by Isabel Arvelo, Andres Gannon, and Alexandra Sniezek."
    left: "&copy; CC-1.0"

  sidebar:
    background: "#D9E3E4"
    pinned: true
    align: center

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/about.qmd
        text: About
      - href: content/Papers.qmd
        text: Paper
      - section: "Data"
        contents:
          - href: content/PDF.qmd
            text: pdf
          - href: content/CSV.qmd
            text: csv
          - href: content/TXT.qmd
            text: txt
      - href: content/Selected_Viz.qmd
        text: Visualizations         

format:
  html:
    theme:
      light: [simplex, theme.scss]
      dark: [simplex, theme-dark.scss]

filters:
  - include-files.lua
  - quarto

execute:
  freeze: auto