project:
  type: website

website:
  navbar: false
  title: "Military Doctrines"
  favicon: images/favicon.ico

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    background: "#D9E3E4"
    pinned: true
    align: center

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/about.qmd
        text: About
      - href: content/Papers.qmd
        text: Paper
      - href: content/Data.qmd
        text: Data
      - section: "Data"
        contents:
          - href: content/PDF.qmd
            text: PDF
          - href: content/CSV.qmd
            text: CSV
          - href: content/TXT.qmd
            text: TXT

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]

filters:
  - include-files.lua
  - quarto

execute:
  freeze: auto


